# Generated by Django 5.1.3 on 2024-11-27 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CajaChica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('saldo_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingresos_totales', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gastos_totales', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('saldo_final', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('cerrado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Fondo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fondo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_local', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rendicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_requerimiento', models.CharField(max_length=50)),
                ('persona', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('numero_transferencia', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto_nombre', models.CharField(max_length=255)),
                ('nivel', models.IntegerField(choices=[(1, 'Nivel 1'), (2, 'Nivel 2'), (3, 'Nivel 3')])),
                ('id_concepto_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subconceptos', to='myapp.concepto')),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('concepto', models.CharField(max_length=255)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('moneda', models.CharField(max_length=50)),
                ('codigo_operacion', models.CharField(max_length=50)),
                ('observacion', models.TextField()),
                ('id_fondo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.fondo')),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField()),
                ('nombre_proveedor', models.CharField(max_length=255)),
                ('tipo_comprobante', models.CharField(max_length=50)),
                ('tipo_pago', models.CharField(max_length=50)),
                ('fecha_operacion', models.DateField()),
                ('codigo_operacion', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('observacion', models.TextField()),
                ('concepto_nivel_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nivel_1', to='myapp.concepto')),
                ('concepto_nivel_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nivel_2', to='myapp.concepto')),
                ('concepto_nivel_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nivel_3', to='myapp.concepto')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.local')),
                ('id_rendicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.rendicion')),
            ],
        ),
    ]
