# Generated by Django 5.1.3 on 2024-11-28 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_ingreso_local_alter_gasto_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingreso',
            name='concepto',
        ),
    ]
