# Generated by Django 5.1.3 on 2024-11-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_ingreso_codigo_operacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='codigo_operacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='fecha_operacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='nombre_proveedor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='tipo_comprobante',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='tipo_pago',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
