# Generated by Django 5.1.3 on 2024-12-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_gasto_codigo_operacion_alter_gasto_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingreso',
            name='fecha',
        ),
        migrations.AddField(
            model_name='ingreso',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
