# Generated by Django 5.1.3 on 2024-12-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_ingreso_fecha_ingreso_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='fecha_gasto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
