# Generated by Django 5.1.3 on 2024-12-06 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_gasto_fecha_gasto_alter_gasto_fecha_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='descripcion',
        ),
    ]
