# Generated by Django 5.1.3 on 2024-12-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_gasto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='importe',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=10),
            preserve_default=False,
        ),
    ]
