# Generated by Django 5.1.3 on 2024-12-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_gasto_importe'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='moneda',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
