# Generated by Django 5.1.3 on 2024-12-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_ingreso_fecha_operacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendicion',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
