# Generated by Django 5.1.3 on 2024-12-13 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_rendicion_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='id_rendicion',
        ),
        migrations.AddField(
            model_name='rendicion',
            name='gasto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendiciones', to='myapp.gasto'),
        ),
    ]
