# Generated by Django 5.1.3 on 2024-12-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_gasto_id_rendicion_rendicion_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='numero_comprobante',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
