# Generated by Django 5.1.3 on 2024-12-17 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_gasto_numero_comprobante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rendicion',
            old_name='fecha',
            new_name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='rendicion',
            name='codigo_requerimiento',
        ),
        migrations.RemoveField(
            model_name='rendicion',
            name='metodo_pago',
        ),
        migrations.RemoveField(
            model_name='rendicion',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='rendicion',
            name='numero_transferencia',
        ),
        migrations.RemoveField(
            model_name='rendicion',
            name='persona',
        ),
        migrations.AddField(
            model_name='rendicion',
            name='apellidos_nombres_proveedor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rendicion',
            name='concepto_nivel_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nivel_1_rendicion', to='myapp.concepto'),
        ),
        migrations.AddField(
            model_name='rendicion',
            name='concepto_nivel_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nivel_2_rendicion', to='myapp.concepto'),
        ),
        migrations.AddField(
            model_name='rendicion',
            name='concepto_nivel_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nivel_3_rendicion', to='myapp.concepto'),
        ),
        migrations.AddField(
            model_name='rendicion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rendicion',
            name='fecha_operacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rendicion',
            name='importe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rendicion',
            name='numero_requerimiento',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
