# Generated by Django 5.1.3 on 2024-12-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_rename_fecha_rendicion_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='rendido',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
