# Generated by Django 5.1.3 on 2024-12-24 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_gasto_rendido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='id_fondo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.fondo'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
