# Generated by Django 5.1.3 on 2024-12-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_ingreso_id_fondo_alter_ingreso_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendicion',
            name='tipo_comprobante',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
