# Generated by Django 5.1.3 on 2024-12-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_proveedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='nombre_proveedor',
            new_name='razon_social',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nombre_comercial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='ruc_dni',
            field=models.CharField(default=10, max_length=13, unique=True),
            preserve_default=False,
        ),
    ]
