# Generated by Django 5.1.3 on 2025-01-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_rename_nombre_proveedor_proveedor_razon_social_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='fecha_emision_comprobante',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gasto',
            name='num_comprobante',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='gasto',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
