# Generated by Django 5.1.3 on 2025-01-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_gasto_fecha_emision_comprobante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='campo_area',
            field=models.CharField(blank=True, choices=[('Sistemas', 'Sistemas'), ('Academico', 'Academico'), ('Imagen', 'Imagen'), ('Gerencia', 'Gerencia'), ('Administracion', 'Administracion'), ('Marketing', 'Marketing'), ('Ventas', 'Ventas')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gasto',
            name='id_requerimiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
