# Generated by Django 5.1.3 on 2025-01-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_gasto_campo_area_gasto_id_requerimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='extorno',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
