# Generated by Django 5.1.3 on 2025-01-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_ingreso_extorno'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='nombre_contacto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='numero_cuenta_bancaria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
