# Generated by Django 5.1.3 on 2025-01-08 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_proveedor_nombre_contacto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='numero_serie',
        ),
    ]
