# Generated by Django 5.1.3 on 2025-01-09 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_gasto_campo_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='nombre_proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='myapp.proveedor'),
        ),
    ]
