# Generated by Django 5.1.3 on 2025-01-09 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_gasto_nombre_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendicion',
            name='apellidos_nombres_proveedor',
        ),
    ]
