# Generated by Django 5.1.3 on 2025-01-09 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_remove_rendicion_apellidos_nombres_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendicion',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendiciones', to='myapp.proveedor'),
        ),
    ]
