# Generated by Django 5.1.3 on 2025-01-10 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_gasto_usuario_creador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendicion',
            name='gasto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendiciones_gasto', to='myapp.gasto'),
        ),
        migrations.AlterField(
            model_name='rendicion',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendiciones_proveedor', to='myapp.proveedor'),
        ),
    ]
