# Generated by Django 5.1.3 on 2025-01-10 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_alter_rendicion_gasto_alter_rendicion_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendicion',
            name='proveedor',
        ),
    ]
