# Generated by Django 5.1.3 on 2025-01-10 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_remove_rendicion_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendicion',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendiciones_proveedor', to='myapp.proveedor'),
        ),
    ]
