# Generated by Django 5.1.3 on 2025-01-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_rendicion_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='num_requerimiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
