# Generated by Django 5.1.3 on 2025-01-22 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_gasto_num_requerimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='numero_cuenta_bancaria',
        ),
    ]
