# Generated by Django 5.1.3 on 2025-01-22 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_remove_proveedor_numero_cuenta_bancaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_banco', models.CharField(max_length=255)),
                ('numero_cuenta', models.CharField(max_length=50, unique=True)),
                ('tipo_cuenta', models.CharField(choices=[('ahorros', 'Cuenta de Ahorros'), ('corriente', 'Cuenta Corriente'), ('otro', 'Otro')], default='ahorros', max_length=50)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_bancarias', to='myapp.proveedor')),
            ],
        ),
    ]
