# Generated by Django 5.1.3 on 2025-01-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_cuentabancaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentabancaria',
            name='cci',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
