# Generated by Django 5.1.3 on 2025-01-29 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_ingreso_banco'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_banco', to='myapp.banco'),
        ),
    ]
