# Generated by Django 5.1.3 on 2025-01-29 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_gasto_banco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('numero_cuotas', models.PositiveIntegerField()),
                ('tea', models.DecimalField(decimal_places=2, help_text='Tasa Efectiva Anual (%)', max_digits=5)),
                ('analista', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('proceso', 'En proceso'), ('terminado', 'Terminado')], default='proceso', max_length=10)),
                ('prestamo_nuevo', models.BooleanField(default=True)),
                ('cuota_actual', models.PositiveIntegerField(default=1)),
                ('banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos', to='myapp.banco')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos', to='myapp.proveedor')),
            ],
        ),
        migrations.AddField(
            model_name='ingreso',
            name='prestamo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos', to='myapp.prestamo'),
        ),
    ]
