# Generated by Django 5.1.3 on 2025-01-29 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_prestamo_ingreso_prestamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Monto total del prestamo', max_digits=15),
            preserve_default=False,
        ),
    ]
