# Generated by Django 5.1.3 on 2025-01-30 10:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_fichaingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='dia_pago',
            field=models.PositiveIntegerField(default=1, help_text='Dia del mes en el que se debe pagar la cuota', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos', to='myapp.local'),
        ),
    ]
