# Generated by Django 5.1.3 on 2025-01-30 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_prestamo_dia_pago_prestamo_local'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FichaIngreso',
        ),
        migrations.RemoveField(
            model_name='ingreso',
            name='prestamo',
        ),
        migrations.DeleteModel(
            name='Prestamo',
        ),
    ]
