# Generated by Django 5.1.3 on 2025-01-30 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_delete_fichaingreso_remove_ingreso_prestamo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('numero_cuotas', models.PositiveIntegerField()),
                ('tea', models.DecimalField(decimal_places=2, max_digits=5)),
                ('analista', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=50)),
                ('prestamo_nuevo', models.BooleanField()),
                ('cuota_actual', models.PositiveIntegerField()),
                ('dia_pago', models.PositiveIntegerField(default=1)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.banco')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.local')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.proveedor')),
            ],
        ),
    ]
