# Generated by Django 5.1.3 on 2025-01-30 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0047_prestamo"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingreso",
            name="prestamo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ingresos",
                to="myapp.prestamo",
            ),
        ),
    ]
