# Generated by Django 5.1.3 on 2025-01-30 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0048_ingreso_prestamo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prestamo",
            name="prestamo_nuevo",
        ),
        migrations.CreateModel(
            name="SaldoInicial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monto_saldo_inicial",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Saldo inicial del usuario",
                        max_digits=15,
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saldo_inicial",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
