# Generated by Django 5.1.3 on 2025-01-31 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0049_remove_prestamo_prestamo_nuevo_saldoinicial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gasto",
            name="prestamo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gastos",
                to="myapp.prestamo",
            ),
        ),
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cuota", models.PositiveIntegerField()),
                ("monto_pagado", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha_pago", models.DateField()),
                (
                    "saldo_restante",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "prestamo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos",
                        to="myapp.prestamo",
                    ),
                ),
            ],
        ),
    ]
