# Generated by Django 5.1.3 on 2025-01-31 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0051_prestamo_monto_cuota"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pago",
            name="saldo_restante",
        ),
    ]
