# Generated by Django 5.1.3 on 2025-02-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0052_remove_pago_saldo_restante"),
    ]

    operations = [
        migrations.CreateModel(
            name="Personal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dni", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "apellidos_nombres",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("celular", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "correo_personal",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "correo_corporativo",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("direccion", models.CharField(blank=True, max_length=255, null=True)),
                ("periodo_inicio", models.DateField(blank=True, null=True)),
                ("periodo_fin", models.DateField(blank=True, null=True)),
                (
                    "tipo_trabajador",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "tipo_contrato",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "tipo_pago",
                    models.CharField(
                        blank=True,
                        choices=[("efectivo", "Efectivo"), ("deposito", "Depósito")],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "nombre_cuenta",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "numero_cuenta",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "asignacion_familiar",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("ocupacion", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "remuneracion",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "regimen_salud",
                    models.CharField(
                        blank=True,
                        choices=[("essalud", "EsSalud"), ("sis", "SIS")],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "regimen_pensionario",
                    models.CharField(
                        blank=True,
                        choices=[("onp", "ONP"), ("afp", "AFP")],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "situacion_educativa",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tipo_instruccion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "institucion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "carrera_estudio",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ano_egreso", models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
    ]
