# Generated by Django 5.1.3 on 2025-02-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0055_gasto_gasto_origen_ingreso_gasto_origen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personal",
            name="remuneracion",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
    ]
