# Generated by Django 5.1.3 on 2025-02-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0056_alter_personal_remuneracion"),
    ]

    operations = [
        migrations.AddField(
            model_name="personal",
            name="regimen_pensionario_details",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
