# Generated by Django 5.1.3 on 2025-02-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0057_personal_regimen_pensionario_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="personal",
            name="cci",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
