# Generated by Django 5.1.3 on 2025-02-19 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0058_personal_cci"),
    ]

    operations = [
        migrations.AddField(
            model_name="saldoinicial",
            name="monto_saldo_inicial_yape",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Saldo inicial del usuario yape",
                max_digits=15,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="rendicion",
            name="gasto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rendiciones_gasto",
                to="myapp.gasto",
            ),
        ),
        migrations.AlterField(
            model_name="rendicion",
            name="proveedor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rendiciones_proveedor",
                to="myapp.proveedor",
            ),
        ),
    ]
