# Generated by Django 5.1.3 on 2025-02-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0060_ingreso_importe_efectivo_ingreso_importe_yape"),
    ]

    operations = [
        migrations.AddField(
            model_name="saldoinicial",
            name="caja_cerrada",
            field=models.BooleanField(
                default=False, help_text="Indica si la caja del usuario está cerrada"
            ),
        ),
        migrations.AddField(
            model_name="saldoinicial",
            name="fecha_cierre",
            field=models.DateField(
                blank=True, help_text="Fecha en la que se cerró la caja", null=True
            ),
        ),
    ]
