# Generated by Django 5.1.3 on 2025-02-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0061_saldoinicial_caja_cerrada_saldoinicial_fecha_cierre"),
    ]

    operations = [
        migrations.AddField(
            model_name="personal",
            name="turno_manana_fin",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="personal",
            name="turno_manana_inicio",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="personal",
            name="turno_tarde_fin",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="personal",
            name="turno_tarde_inicio",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
