# Generated by Django 5.1.3 on 2025-03-24 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0064_prestamo_notas"),
    ]

    operations = [
        migrations.AddField(
            model_name="personal",
            name="local",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="local_trabajo",
                to="myapp.local",
            ),
        ),
        migrations.AlterField(
            model_name="gasto",
            name="local",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gastos_local",
                to="myapp.local",
            ),
        ),
        migrations.AlterField(
            model_name="ingreso",
            name="local",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ingresos_local",
                to="myapp.local",
            ),
        ),
        migrations.AlterField(
            model_name="personal",
            name="regimen_pensionario",
            field=models.CharField(
                blank=True,
                choices=[("ninguno", "Ninguno"), ("onp", "ONP"), ("afp", "AFP")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="personal",
            name="regimen_salud",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ninguno", "Ninguno"),
                    ("essalud", "EsSalud"),
                    ("sis", "SIS"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
