# Generated by Django 5.1.3 on 2025-03-14 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0064_prestamo_notas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='regimen_pensionario',
            field=models.CharField(blank=True, choices=[('ninguno', 'Ninguno'), ('onp', 'ONP'), ('afp', 'AFP')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='regimen_salud',
            field=models.CharField(blank=True, choices=[('ninguno', 'Ninguno'), ('essalud', 'EsSalud'), ('sis', 'SIS')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('recurrencia', models.CharField(choices=[('none', 'No se repite'), ('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual')], default='none', max_length=20)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notas', models.TextField(blank=True)),
                ('pagado', models.BooleanField(default=False)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
    ]
