# Generated by Django 5.1.3 on 2025-03-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0065_personal_local_alter_gasto_local_alter_ingreso_local_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prestamo",
            name="estado",
            field=models.CharField(
                choices=[
                    ("nuevo", "Nuevo"),
                    ("proceso", "En proceso"),
                    ("terminado", "Terminado"),
                ],
                default="nuevo",
                max_length=50,
            ),
        ),
    ]
