# Generated by Django 5.1.3 on 2025-03-14 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0065_alter_personal_regimen_pensionario_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evento',
        ),
    ]
