# Generated by Django 5.1.3 on 2025-03-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0066_alter_prestamo_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="gasto",
            name="fecha_rendido",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="prestamo",
            name="estado",
            field=models.CharField(
                choices=[("proceso", "En proceso"), ("terminado", "Terminado")],
                default="nuevo",
                max_length=50,
            ),
        ),
    ]
