# Generated by Django 5.1.3 on 2025-03-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0067_evento_ocurrenciaevento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='prestamo',
            field=models.BooleanField(default=False, verbose_name='Prestamo'),
        ),
    ]
