# Generated by Django 5.1.3 on 2025-03-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0067_gasto_fecha_rendido_alter_prestamo_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="pago",
            name="notas",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="prestamo",
            name="dia_pago",
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name="prestamo",
            name="estado",
            field=models.CharField(
                choices=[("proceso", "En proceso"), ("terminado", "Terminado")],
                default="terminado",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="prestamo",
            name="fecha_vencimiento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="prestamo",
            name="monto",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="prestamo",
            name="monto_cuota",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
