# Generated by Django 5.1.3 on 2025-03-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0068_pago_notas_alter_prestamo_dia_pago_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cuentabancaria",
            name="numero_cuenta",
            field=models.CharField(max_length=50),
        ),
    ]
