# Generated by Django 5.1.3 on 2025-04-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0070_evento_ocurrenciaevento"),
    ]

    operations = [
        migrations.AddField(
            model_name="prestamo",
            name="tcea",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="gasto",
            name="campo_area",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sistemas", "Sistemas"),
                    ("Academico", "Academico"),
                    ("Imagen", "Imagen"),
                    ("Gerencia", "Gerencia"),
                    ("Administracion", "Administracion"),
                    ("Marketing", "Marketing"),
                    ("Ventas", "Ventas"),
                    ("Almacen", "Almacen"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
