# Generated by Django 5.1.3 on 2025-04-03 16:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0071_prestamo_tcea_alter_gasto_campo_area"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gasto",
            name="fecha_registro",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ingreso",
            name="fecha_registro",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
