# Generated by Django 5.1.3 on 2025-04-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0072_alter_gasto_fecha_registro_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personal",
            name="link_drive",
            field=models.URLField(
                blank=True, null=True, verbose_name="Enlace de Google Drive"
            ),
        ),
        migrations.AlterField(
            model_name="gasto",
            name="campo_area",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sistemas", "Sistemas"),
                    ("Academico", "Academico"),
                    ("Imagen", "Imagen"),
                    ("Gerencia", "Gerencia"),
                    ("Administracion", "Administracion"),
                    ("Marketing", "Marketing"),
                    ("Ventas", "Ventas"),
                    ("Almacen", "Almacen"),
                    ("Tesoreria", "Tesoreria"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
