# Generated by Django 5.1.3 on 2025-04-09 17:34

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0073_personal_link_drive_alter_gasto_campo_area"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalGasto",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("fecha_gasto", models.DateField(blank=True, null=True)),
                (
                    "tipo_comprobante",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "num_comprobante",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("fecha_emision_comprobante", models.DateField(blank=True, null=True)),
                (
                    "numero_comprobante",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("tipo_pago", models.CharField(blank=True, max_length=50, null=True)),
                ("fecha_operacion", models.DateField(blank=True, null=True)),
                (
                    "codigo_operacion",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("observacion", models.TextField(blank=True, null=True)),
                ("importe", models.DecimalField(decimal_places=2, max_digits=10)),
                ("moneda", models.CharField(max_length=50)),
                ("rendido", models.BooleanField(blank=True, default=False, null=True)),
                ("fecha_rendido", models.DateField(blank=True, null=True)),
                (
                    "id_requerimiento",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "num_requerimiento",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "campo_area",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Sistemas", "Sistemas"),
                            ("Academico", "Academico"),
                            ("Imagen", "Imagen"),
                            ("Gerencia", "Gerencia"),
                            ("Administracion", "Administracion"),
                            ("Marketing", "Marketing"),
                            ("Ventas", "Ventas"),
                            ("Almacen", "Almacen"),
                            ("Tesoreria", "Tesoreria"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "campo_mes",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Enero", "Enero"),
                            ("Febrero", "Febrero"),
                            ("Marzo", "Marzo"),
                            ("Abril", "Abril"),
                            ("Mayo", "Mayo"),
                            ("Junio", "Junio"),
                            ("Julio", "Julio"),
                            ("Agosto", "Agosto"),
                            ("Septiembre", "Septiembre"),
                            ("Octubre", "Octubre"),
                            ("Noviembre", "Noviembre"),
                            ("Diciembre", "Diciembre"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "banco",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="myapp.banco",
                    ),
                ),
                (
                    "concepto_nivel_1",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="myapp.concepto",
                    ),
                ),
                (
                    "concepto_nivel_2",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="myapp.concepto",
                    ),
                ),
                (
                    "concepto_nivel_3",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="myapp.concepto",
                    ),
                ),
                (
                    "gasto_origen",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="myapp.gasto",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "local",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="myapp.local",
                    ),
                ),
                (
                    "nombre_proveedor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="myapp.proveedor",
                    ),
                ),
                (
                    "prestamo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="myapp.prestamo",
                    ),
                ),
                (
                    "usuario_creador",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical gasto",
                "verbose_name_plural": "historical gastos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalIngreso",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("fecha_ingreso", models.DateField(blank=True, null=True)),
                ("importe", models.DecimalField(decimal_places=2, max_digits=10)),
                ("metodo_pago", models.CharField(blank=True, max_length=50, null=True)),
                ("moneda", models.CharField(max_length=50)),
                ("fecha_operacion", models.DateField(blank=True, null=True)),
                (
                    "codigo_operacion",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("observacion", models.TextField(blank=True, null=True)),
                ("extorno", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "importe_efectivo",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "importe_yape",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "banco",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="myapp.banco",
                    ),
                ),
                (
                    "gasto_origen",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="myapp.gasto",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_fondo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="myapp.fondo",
                    ),
                ),
                (
                    "local",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="myapp.local",
                    ),
                ),
                (
                    "prestamo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="myapp.prestamo",
                    ),
                ),
                (
                    "usuario_creador",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical ingreso",
                "verbose_name_plural": "historical ingresos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
