# Generated by Django 5.1.3 on 2025-04-10 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0074_historicalgasto_historicalingreso"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistorialGasto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_id", models.IntegerField(blank=True, null=True)),
                ("fecha_registro", models.DateField(blank=True, null=True)),
                ("fecha_gasto", models.DateField(blank=True, null=True)),
                (
                    "tipo_comprobante",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "num_comprobante",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("fecha_emision_comprobante", models.DateField(blank=True, null=True)),
                (
                    "numero_comprobante",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("tipo_pago", models.CharField(blank=True, max_length=50, null=True)),
                ("fecha_operacion", models.DateField(blank=True, null=True)),
                (
                    "codigo_operacion",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("observacion", models.TextField(blank=True, null=True)),
                ("importe", models.DecimalField(decimal_places=2, max_digits=10)),
                ("moneda", models.CharField(max_length=50)),
                ("rendido", models.BooleanField(blank=True, default=False, null=True)),
                ("fecha_rendido", models.DateField(blank=True, null=True)),
                (
                    "id_requerimiento",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "num_requerimiento",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "campo_area",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Sistemas", "Sistemas"),
                            ("Academico", "Academico"),
                            ("Imagen", "Imagen"),
                            ("Gerencia", "Gerencia"),
                            ("Administracion", "Administracion"),
                            ("Marketing", "Marketing"),
                            ("Ventas", "Ventas"),
                            ("Almacen", "Almacen"),
                            ("Tesoreria", "Tesoreria"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "campo_mes",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Enero", "Enero"),
                            ("Febrero", "Febrero"),
                            ("Marzo", "Marzo"),
                            ("Abril", "Abril"),
                            ("Mayo", "Mayo"),
                            ("Junio", "Junio"),
                            ("Julio", "Julio"),
                            ("Agosto", "Agosto"),
                            ("Septiembre", "Septiembre"),
                            ("Octubre", "Octubre"),
                            ("Noviembre", "Noviembre"),
                            ("Diciembre", "Diciembre"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("fecha_eliminacion", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario_creador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="historial_gastos_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistorialIngreso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_id", models.IntegerField(blank=True, null=True)),
                ("fecha_registro", models.DateField(blank=True, null=True)),
                ("fecha_ingreso", models.DateField(blank=True, null=True)),
                ("importe", models.DecimalField(decimal_places=2, max_digits=10)),
                ("metodo_pago", models.CharField(blank=True, max_length=50, null=True)),
                ("moneda", models.CharField(max_length=50)),
                ("fecha_operacion", models.DateField(blank=True, null=True)),
                (
                    "codigo_operacion",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("observacion", models.TextField(blank=True, null=True)),
                ("extorno", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "importe_efectivo",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "importe_yape",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("fecha_eliminacion", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario_creador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="historial_ingresos_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
