# Generated by Django 5.1.3 on 2025-04-10 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0075_historialgasto_historialingreso"),
    ]

    operations = [
        migrations.AddField(
            model_name="historialgasto",
            name="concepto_nivel_1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historialgasto_concepto_nivel_1",
                to="myapp.concepto",
            ),
        ),
        migrations.AddField(
            model_name="historialgasto",
            name="concepto_nivel_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historialgasto_concepto_nivel_2",
                to="myapp.concepto",
            ),
        ),
        migrations.AddField(
            model_name="historialgasto",
            name="concepto_nivel_3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historialgasto_concepto_nivel_3",
                to="myapp.concepto",
            ),
        ),
        migrations.AddField(
            model_name="historialgasto",
            name="nombre_proveedor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="historialgasto_proveedor",
                to="myapp.proveedor",
            ),
        ),
    ]
