# Generated by Django 5.1.3 on 2025-04-28 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0076_historialgasto_concepto_nivel_1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrestamoIrregular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_prestamo", models.DateField(verbose_name="Fecha de Prestamo")),
                ("analista", models.CharField(max_length=100, verbose_name="Analista")),
                (
                    "monto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Monto del Prestamo",
                    ),
                ),
                (
                    "dia_pago",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Dia de Pago"
                    ),
                ),
                (
                    "interes_mensual",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Interes Mensual",
                    ),
                ),
                (
                    "notas",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("proceso", "En proceso"), ("terminado", "Terminado")],
                        default="proceso",
                        max_length=50,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "banco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.banco",
                        verbose_name="Banco",
                    ),
                ),
                (
                    "local",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.local",
                        verbose_name="Local",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.proveedor",
                        verbose_name="Proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prestamo Irregular",
                "verbose_name_plural": "Prestamos Irregulares",
                "ordering": ["-fecha_prestamo"],
            },
        ),
    ]
