# Generated by Django 5.1.3 on 2025-04-28 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0077_prestamoirregular"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalingreso",
            name="prestamo_irregular",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="myapp.prestamoirregular",
            ),
        ),
        migrations.AddField(
            model_name="ingreso",
            name="prestamo_irregular",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ingresos_irregulares",
                to="myapp.prestamoirregular",
            ),
        ),
    ]
