# Generated by Django 5.1.3 on 2025-04-28 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0078_historicalingreso_prestamo_irregular_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PagoIrregular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_pago",
                    models.CharField(
                        choices=[("capital", "Capital"), ("intereses", "Intereses")],
                        max_length=20,
                    ),
                ),
                ("monto_pagado", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha_pago", models.DateField()),
                ("notas", models.TextField(blank=True, null=True)),
                (
                    "prestamo_irregular",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos_irregulares",
                        to="myapp.prestamoirregular",
                    ),
                ),
            ],
        ),
    ]
