# Generated by Django 5.1.3 on 2025-04-29 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0079_pagoirregular"),
    ]

    operations = [
        migrations.AddField(
            model_name="gasto",
            name="prestamo_irregular",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gastos_irregulares",
                to="myapp.prestamoirregular",
            ),
        ),
        migrations.AddField(
            model_name="historicalgasto",
            name="prestamo_irregular",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="myapp.prestamoirregular",
            ),
        ),
    ]
